Repository mobi-projects/yeogi-client, pull requests merged in 2024-08, with the labels that each got.

#125 YG-172 [refactor] : floating bar
  apis/api.utils.ts
  apis/postApi.ts
  apis/userApi.ts
  app/(afterLogin)/post/detail/[postId]/_components/comment/commentBox.tsx
  app/(afterLogin)/post/detail/[postId]/_components/comment/type.ts
  app/(afterLogin)/post/detail/[postId]/_components/floating/floatingBar.tsx
  app/(afterLogin)/post/detail/[postId]/_components/floating/floatingBarHandler.ts
  app/(afterLogin)/post/detail/[postId]/_components/floating/floatingButton.tsx
  app/(afterLogin)/post/detail/[postId]/_components/floating/type.ts
  app/(afterLogin)/post/detail/[postId]/_components/postDetailClient.tsx
  app/(afterLogin)/post/detail/[postId]/_components/section/commentSection.tsx
  app/(afterLogin)/post/detail/[postId]/_components/section/type.ts
  app/(afterLogin)/post/detail/[postId]/page.tsx
  components/commons/deleteModal.tsx
  hook/floating/type.ts
  hook/floating/useDeleteHandler.ts
  hook/floating/useIconState.ts
  hook/floating/useIconStateHandler.ts
  hook/floating/useLikeHandler.ts
  hook/floating/useScrollTopHandler.ts
  hook/floating/useShareHandler.ts
  hook/floating/useUpdateHandler.ts
  hook/type.ts
  hook/useHandleScroll.ts
  hook/usePostLikeHandler.ts
  libs/zustand/floating.ts
  libs/zustand/post.ts
  libs/zustand/type.ts
Labels: 🟢 feat, 🐞 fix, 💡 refactor

#126 YG-190 [refactor] : optimization
  app/_components/polaroid.tsx
  app/globals.css
  app/layout.tsx
  next.config.mjs
  tailwind.config.ts
Labels: Low, 🎁 style, 💡 refactor

#127 YG-178 [refactor] : NextAuth 설정 및 middleware 재설정 , typeGuard 생성
  apis/api.utils.ts
  apis/auth/oauthApi.ts
  apis/auth/socialSignup.ts
  apis/auth/token/access.utils.ts
  apis/userApi.ts
  app/api/auth/[...nextauth]/route.ts
  app/auth/_components/signin/socialLoginLayout.tsx
  app/auth/addInfo/page.tsx
  app/auth/page.tsx
  app/layout.tsx
  app/nextAuthSession.tsx
  app/theme/page.tsx
  components/layouts/_components/userDialog.tsx
  components/layouts/header.tsx
  hook/floating/useIconStateHandler.ts
  hook/useCheckNicknameExists.ts
  libs/reactQuery/type.ts
  libs/reactQuery/useAuthMutation.ts
  middleware.ts
  next.config.mjs
  package-lock.json
  package.json
  tsconfig.json
  types/next-auth.d.ts
  utils/typeGuard.ts
Labels: medium, 🟢 feat, 🔴 Remove, 💡 refactor

#129 YG - 192 [refactor] : nextauth-addInfoForm 수정 & Header 리펙토링
  apis/auth/signin.ts
  apis/userApi.ts
  app/(afterLogin)/post/_components/region/addressAutoComplete.tsx
  app/(afterLogin)/post/_components/region/countrySearchBar.tsx
  app/api/auth/[...nextauth]/route.ts
  app/auth/_components/signin/signinForm.tsx
  app/auth/_components/signup/addInfoForm.tsx
  app/auth/_components/signup/ageGenderInputForm.tsx
  app/auth/_components/signup/emailInputForm.tsx
  app/auth/_components/signup/nicknameInputForm.tsx
  app/auth/_components/signup/type.ts
  components/commons/rankCard.tsx
  components/commons/successToFailModal.tsx
  components/layouts/_components/headerLogin.tsx
  components/layouts/_components/headerSearch.tsx
  components/layouts/_components/postWriteBtn.tsx
  components/layouts/_components/type.ts
  components/layouts/_components/userDialog.tsx
  components/layouts/header.tsx
  components/queryProvider.tsx
  hook/useCheckNicknameExists.ts
  libs/reactQuery/useAuthMutation.ts
  libs/zustand/modal.ts
  libs/zustand/type.ts
  middleware.ts
Labels: medium, 🔴 Remove, 🐞 fix, 💡 refactor

#130 YG-188 [feat] : Pin-in and issue pins when writing posts
  apis/mapApi.ts
  apis/postApi.ts
  apis/type.ts
  app/(afterLogin)/post/_components/common/useCommonPost/useCommonSubmitHandling.ts
  app/(afterLogin)/user/[userId]/_components/myMap/mapPin.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/myPinList.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/pin.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/pinCard.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/pinCardGrid.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/pinListHeader.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/pinListPagination.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/pinModal.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/pinThumbnail.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/type.ts
  app/(afterLogin)/user/[userId]/_components/myMap/updatedWorldMapModal.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/worldMap.tsx
  app/(afterLogin)/user/[userId]/_components/profile/profile.tsx
  app/(afterLogin)/user/[userId]/_components/profile/profileDetails.tsx
  app/(afterLogin)/user/[userId]/_components/profile/type.ts
  app/(afterLogin)/user/[userId]/_components/type.ts
  app/(afterLogin)/user/[userId]/_components/userClient.tsx
  app/(afterLogin)/user/[userId]/page.tsx
  app/_components/userRecommendation/type.ts
  libs/queryClient/pinQuery.ts
  libs/zustand/pin.ts
  libs/zustand/type.ts
  next.config.mjs
  public/icons/next.svg
  public/icons/prev.svg
  public/images/pin.svg
  types/post.ts
  utils/map.utils.ts
Labels: 🟢 feat
