Repository mobi-projects/yeogi-client, pull requests merged in 2024-07, with the labels that each got.

#73 YG-102 [feat]: theme banner
  app/(beforeLogin)/search/page.tsx
  app/_components/mainThemeBanner.tsx
  app/page.tsx
  constants/theme.ts
  public/images/ACTIVITY.svg
  public/images/COST_EFFECTIVENESS.svg
  public/images/EATING.svg
  public/images/HOT_PLACE.svg
  public/images/PACKAGE.svg
  public/images/REST.svg
  public/images/SHOPPING.svg
  public/images/SIGHTSEEING.svg
  public/images/SUPER_LUXURY.svg
  tailwind.config.ts
Labels: medium, 🟢 feat

#75 YG - 107 [feat] : skeleton 생성 및 debounce 설정
  app/_components/mainPosts.tsx
  components/commons/skeleton.tsx
  package-lock.json
  package.json
Labels: medium, 🟢 feat

#74 YG-108 [refactor]: refactor address, change korean, delete country
  app/(afterLogin)/createPost/_components/addressSearch/address.util.ts
  app/(afterLogin)/createPost/_components/addressSearch/addressAutoComplete.tsx
  utils/fetchFormAPI.ts
  utils/googleMapsUtils.ts
Labels: 💡 refactor

#76 YG-106 [refactor]: create & update post
  README.md
  apis/postApi.ts
  apis/type.ts
  app/(afterLogin)/createPost/_components/addressSearch/type.ts
  app/(afterLogin)/createPost/_components/commonPost.tsx
  app/(afterLogin)/createPost/_components/editor/addressSelection.tsx
  app/(afterLogin)/createPost/_components/editor/editorQuill.tsx
  app/(afterLogin)/createPost/_components/editor/reactQuill.ts
  app/(afterLogin)/createPost/_components/form/formSelector.tsx
  app/(afterLogin)/createPost/_components/form/themeSelection.tsx
  app/(afterLogin)/createPost/_components/form/type.ts
  app/(afterLogin)/createPost/_components/form/upperSelection.tsx
  app/(afterLogin)/createPost/_components/overlay/type.ts
  app/(afterLogin)/createPost/_components/overlay/uploadOverlay.tsx
  app/(afterLogin)/createPost/_components/region/address.util.ts
  app/(afterLogin)/createPost/_components/region/addressAutoComplete.tsx
  app/(afterLogin)/createPost/_components/region/countriesSearch.tsx
  app/(afterLogin)/createPost/_components/region/countrySearchBar.tsx
  app/(afterLogin)/createPost/_components/region/selectContinent.tsx
  app/(afterLogin)/createPost/_components/region/selectedAddress.tsx
  app/(afterLogin)/createPost/_components/region/type.ts
  app/(afterLogin)/createPost/_components/theme/selectedTheme.tsx
  app/(afterLogin)/createPost/_components/type.ts
  app/(afterLogin)/createPost/freeForm/page.tsx
  app/(afterLogin)/createPost/memoForm/page.tsx
  app/(afterLogin)/detailPost/[postId]/_components/postDetail.tsx
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/(afterLogin)/updatePost/[postId]/page.tsx
  app/_components/type.ts
  components/commons/searchDropdown.tsx
  constants/theme.ts
  hook/type.ts
  hook/updatePostFunctions.ts
  hook/useCommonPost.ts
  hook/usePostMutation.ts
  libs/store.ts
  libs/type.ts
  package-lock.json
  public/icons/gps-grey.svg
  public/icons/grey-trash.svg
  styles/editor-content.css
  utils/resetFormData.ts
  utils/sessionStorage.ts
  utils/type.ts
  utils/updatePostFunctions.ts
Labels: medium, 🟢 feat, 🎁 style

#77 YG-112 [feat] : main recommend container
  app/(beforeLogin)/survey/page.tsx
  app/_components/mainSurveyRecommend.tsx
  app/_components/recommendText.tsx
  app/page.tsx
  components/commons/searchBar.tsx
  components/layouts/_components/headerLogin.tsx
  components/layouts/_components/headerNavigate.tsx
  components/layouts/_components/headerSearch.tsx
  components/layouts/_components/type.ts
  components/layouts/header.tsx
  package-lock.json
  package.json
  public/video/recommendVideo.mp4
  public/video/recommendVideo_crop.mp4
  styles/common-button.ts
Labels: medium, 🟢 feat, 💡 refactor

#79 YG - 111 [feat] : suervey page
  apis/auth/oauthApi.ts
  app/(beforeLogin)/survey/_components/surveyIntro.tsx
  app/(beforeLogin)/survey/_components/surveyRecommendText.tsx
  app/(beforeLogin)/survey/_components/surveyResult.tsx
  app/(beforeLogin)/survey/page.tsx
  app/auth/page.tsx
  public/images/airplane.gif
  public/images/서브비주얼.svg
  public/images/캐리어.gif
  styles/color.ts
  tailwind.config.ts
  utils/filterPosts.ts
Labels: medium, 🟢 feat

#78 YG-113 [feat] : recommend postcard
  app/(beforeLogin)/survey/_components/recommendPostCard.tsx
  app/(beforeLogin)/survey/_components/type.ts
  app/_components/mainSurveyRecommend.tsx
  constants/recommendedTextFields.ts
  constants/type.ts
  public/images/comment-tape.svg
  public/images/re-comment-bg.svg
  public/images/re-comment-tape.svg
  public/images/sticker.svg
  public/video/recommendVideo.mp4
  utils/recommendPosts.utils.ts
Labels: High, 🟢 feat

#80 YG-110 [feat]: create survey
  apis/commentApi.ts
  apis/postApi.ts
  app/(beforeLogin)/survey/_components/surveyForm/getRandomQuestion.ts
  app/(beforeLogin)/survey/_components/surveyForm/survey.util.ts
  app/(beforeLogin)/survey/_components/surveyForm/surveyQuestionForm.tsx
  app/(beforeLogin)/survey/_components/surveyForm/surveyStart.tsx
  data/surveyQuestion.ts
  data/type.ts
  hook/useSurvey.ts
  utils/fetchFormAPI.ts
Labels: medium, 🟢 feat, 💡 refactor

#83 YG-118 [refactor] : header
  apis/auth/oauthApi.ts
  app/auth/page.tsx
  components/layouts/_components/headerNavigate.tsx
  components/layouts/_components/headerSearch.tsx
  components/layouts/header.tsx
Labels: medium, 💡 refactor

#82 YG-117 [fix] : post create detail
  apis/auth/oauthApi.ts
  app/(afterLogin)/createPost/_components/calendar/calendar.tsx
  app/(afterLogin)/createPost/_components/commonPost.tsx
  app/(afterLogin)/createPost/_components/form/addressSelection.tsx
  app/(afterLogin)/createPost/_components/form/formSelector.tsx
  app/(afterLogin)/createPost/_components/form/formTextDisplay.tsx
  app/(afterLogin)/createPost/_components/form/selectedTheme.tsx
  app/(afterLogin)/createPost/_components/form/themeSelection.tsx
  app/(afterLogin)/createPost/_components/form/type.ts
  app/(afterLogin)/createPost/_components/overlay/uploadOverlay.tsx
  app/(afterLogin)/createPost/_components/region/addressAutoComplete.tsx
  app/(afterLogin)/createPost/_components/region/countriesSearch.tsx
  app/(afterLogin)/createPost/_components/region/selectContinent.tsx
  app/(afterLogin)/createPost/_components/region/selectedAddress.tsx
  app/(afterLogin)/createPost/_components/theme/type.ts
  app/(afterLogin)/createPost/memoForm/page.tsx
  app/(afterLogin)/detailPost/[postId]/_components/postDetail.tsx
  app/(afterLogin)/updatePost/[postId]/page.tsx
  app/(beforeLogin)/search/page.tsx
  app/_components/mainThemeBanner.tsx
  components/commons/searchDropdown.tsx
  hook/updatePostFunctions.ts
  hook/useCommonPost.ts
  hook/useFloatingBarHandler.ts
  libs/store.ts
  libs/type.ts
Labels: medium, 🐞 fix, 🎁 style

#84 YG-116 [refactor]: survey
  apis/postApi.ts
  app/(afterLogin)/createPost/_components/region/countrySearchBar.tsx
  app/(afterLogin)/detailPost/[postId]/_components/postDetail.tsx
  app/(beforeLogin)/survey/_components/getRandomQuestion.ts
  app/(beforeLogin)/survey/_components/recommendPostCard.tsx
  app/(beforeLogin)/survey/_components/survey.util.ts
  app/(beforeLogin)/survey/_components/surveyIntro.tsx
  app/(beforeLogin)/survey/_components/surveyQuestionForm.tsx
  app/(beforeLogin)/survey/_components/surveyRecommendText.tsx
  app/(beforeLogin)/survey/_components/surveyResult.tsx
  app/(beforeLogin)/survey/page.tsx
  components/commons/postCard.tsx
  hook/useSurvey.ts
  libs/themeStore.ts
  libs/type.ts
  next.config.mjs
  tailwind.config.ts
Labels: medium, 💡 refactor

#86 YG-120 [fix]: tripStartDate, tripEndDate
  hook/useCommonPost.ts
Labels: 🐞 fix

#85 YG-119 [style] : responsive main-page
  app/_components/mainDesc.tsx
  app/_components/mainImages.tsx
  app/_components/mainIntro.tsx
  app/_components/mainPosts.tsx
  app/_components/mainSearch.tsx
  app/_components/mainSurveyRecommend.tsx
  app/_components/mainThemeBanner.tsx
  app/_components/polaroid.tsx
  app/_components/recommendText.tsx
  app/_components/type.ts
  app/page.tsx
  components/commons/searchBar.tsx
  components/commons/searchDropdownMap.tsx
  components/commons/type.ts
  public/images/search-bg.svg
  tailwind.config.ts
Labels: medium, 🎁 style

#87 YG - 121 [refactor] : header userprofileimage
  app/auth/page.tsx
  components/layouts/_components/headerLogin.tsx
  components/layouts/header.tsx
  components/layouts/type.ts
  libs/loginStore.ts
  libs/type.ts
  next.config.mjs
Labels: medium, 💡 refactor

#88 YG-122 [fix/change] : 🔖 postType 필드 네임 변경 및 적용
  apis/auth/oauthApi.ts
  apis/mockPosts.ts
  apis/postApi.ts
  apis/type.ts
  app/(afterLogin)/createPost/_components/commonPost.tsx
  app/(afterLogin)/createPost/_components/editor/editorQuill.tsx
  app/(afterLogin)/createPost/_components/editor/type.ts
  app/(afterLogin)/createPost/_components/form/formSelector.tsx
  app/(afterLogin)/createPost/_components/form/selectedTheme.tsx
  app/(afterLogin)/createPost/_components/form/type.ts
  app/(afterLogin)/createPost/_components/overlay/type.ts
  app/(afterLogin)/createPost/_components/overlay/uploadOverlay.tsx
  app/(afterLogin)/createPost/_components/type.ts
  app/(afterLogin)/createPost/freeForm/page.tsx
  app/(afterLogin)/createPost/memoForm/page.tsx
  app/(afterLogin)/detailPost/[postId]/_components/floating/type.ts
  app/(afterLogin)/detailPost/[postId]/_components/postDetail.tsx
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/(afterLogin)/detailPost/[postId]/page.tsx
  app/(afterLogin)/updatePost/[postId]/page.tsx
  app/(afterLogin)/user/[userId]/_components/myPost.tsx
  app/(afterLogin)/user/[userId]/page.tsx
  app/(beforeLogin)/search/page.tsx
  app/(beforeLogin)/survey/_components/recommendPostCard.tsx
  app/_components/mainSearch.tsx
  app/_components/mainThemeBanner.tsx
  app/auth/page.tsx
  components/commons/searchDropdown.tsx
  components/commons/type.ts
  constants/theme.ts
  hook/type.ts
  hook/updatePostFunctions.ts
  hook/useFloatingBarHandler.ts
  hook/usePostMutation.ts
  hook/useUpdatePost.ts
  libs/store.ts
  libs/type.ts
  types/post.ts
  types/theme.ts
  utils/commonFormUtils.ts
  utils/filterPosts.ts
  utils/recommendPosts.utils.ts
  utils/resetFormData.ts
  utils/type.ts
Labels: High, 🔖 Rename, 🎁 style

#89 YG-123 [HOT_FIX]: build error
  app/auth/page.tsx
Labels: 🔥 HOTFIX

#90 YG-125 🔖 Rename : 전체 폴더구조 수정
  apis/api.utils.ts
  apis/auth/signin.ts
  apis/commentApi.ts
  apis/mapApi.ts
  apis/postApi.ts
  apis/recommentApi.ts
  apis/userApi.ts
  app/(afterLogin)/createPost/_components/form/formSelector.tsx
  app/(afterLogin)/createPost/_components/region/addressAutoComplete.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/_components/commentContents.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/reComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/postDetail.tsx
  app/(afterLogin)/detailPost/[postId]/date.utils.ts
  app/(afterLogin)/user/[userId]/_components/myMap/worldMap.tsx
  app/(afterLogin)/user/[userId]/page.tsx
  app/(beforeLogin)/search/page.tsx
  app/_components/recommend.utils.ts
  app/auth/_components/signin/addSigninForm.tsx
  app/auth/_components/signin/signinForm.tsx
  app/auth/_components/signin/socialLoginButton.tsx
  app/auth/_components/signin/type.ts
  app/auth/_components/signup/ageButton.tsx
  app/auth/_components/signup/signupForm.tsx
  app/auth/_components/signup/type.ts
  app/auth/page.tsx
  components/commons/button.tsx
  components/commons/pagination.tsx
  components/commons/postCard.tsx
  components/commons/protectedLink.tsx
  components/commons/searchResults.tsx
  components/layouts/_components/headerLogin.tsx
  components/layouts/header.tsx
  constants/theme.ts
  data/countries.ts
  hook/type.ts
  hook/updatePostFunctions.ts
  hook/useCommonPost.ts
  hook/useSignin.ts
  hook/useUpdatePost.ts
  utils/form.utils.ts
  utils/map.utils.ts
  utils/pagination.utils.ts
  utils/reset.utils.ts
  utils/resizeImage.utils.ts
  utils/search.utils.ts
  utils/storage.utils.ts
  utils/tailwind.utils.ts
Labels: 🔖 Rename, 💡 refactor

#91 YG-126 [refactor]: search and pagination
  app/(beforeLogin)/search/page.tsx
  app/_components/mainThemeBanner.tsx
  components/commons/searchBar.tsx
  components/commons/searchDropdown.tsx
  components/commons/searchResults.tsx
  components/commons/type.ts
  components/layouts/header.tsx
  utils/search.utils.ts
Labels: medium, 💡 refactor

#92 YG-128 [refactor] : signin
  app/(afterLogin)/detailPost/[postId]/_components/comment/createComment.tsx
  app/auth/_components/signin/socialLoginButton.tsx
  app/auth/_components/signup/addInfoForm.tsx
  app/auth/_components/signup/ageButton.tsx
  app/auth/_components/signup/genderSelect.tsx
  app/auth/_components/signup/type.ts
  app/auth/page.tsx
  components/commons/protectedLink.tsx
  styles/common-button.ts
Labels: medium, 🟢 feat, 💡 refactor

#94 YG-130 [feat]: real time recommendation
  app/_components/realTimeRecommendation.tsx
  app/_components/recommendPagination.tsx
  app/_components/type.ts
  app/_components/userRecommendation/PostList.tsx
  app/_components/userRecommendation/hoverMoreButton.tsx
  app/_components/userRecommendation/recommendationHeader.tsx
  app/_components/userRecommendation/type.ts
  app/_components/userRecommendation/userRecommendation.tsx
  app/page.tsx
  components/commons/rankCard.tsx
  components/commons/type.ts
  hook/type.ts
  hook/useRecommendPagination.ts
  public/icons/btn_next.svg
  public/icons/btn_prev.svg
  public/icons/gt-BRAND.svg
  public/icons/gt-black.svg
  public/icons/white_gps.svg
  public/images/rankCardThumbnail.svg
  types/post.ts
Labels: medium, 🟢 feat

#95 YG - 129 [feat] : postlike
  apis/commentApi.ts
  apis/postApi.ts
  apis/type.ts
  app/(afterLogin)/createPost/_components/calendar/calendar.tsx
  app/(afterLogin)/createPost/_components/form/formSelector.tsx
  app/(afterLogin)/createPost/_components/form/selectedTheme.tsx
  app/(afterLogin)/createPost/_components/overlay/uploadOverlay.tsx
  app/(afterLogin)/createPost/_components/region/countriesSearch.tsx
  app/(afterLogin)/createPost/_components/region/selectContinent.tsx
  app/(afterLogin)/createPost/_components/region/selectedAddress.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/_components/likeButton.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/_components/likeToComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/floating/floatingBar.tsx
  app/(afterLogin)/detailPost/[postId]/_components/floating/type.ts
  app/(afterLogin)/detailPost/[postId]/page.tsx
  app/(afterLogin)/updatePost/[postId]/page.tsx
  hook/type.ts
  hook/updatePostFunctions.ts
  hook/useCommentLikeHandler.ts
  hook/useCommonPost.ts
  hook/useFloatingBarHandler.ts
  hook/usePostLikeHandler.ts
  hook/useUpdatePost.ts
  libs/likeStore.ts
  libs/loginStore.ts
  libs/postStore.ts
  libs/type.ts
  types/post.ts
Labels: medium, 🟢 feat, 🔖 Rename, 💡 refactor

#93 YG-132 [re-feat] : search page
  apis/commentApi.ts
  apis/recommentApi.ts
  app/(afterLogin)/detailPost/[postId]/_components/comment/_components/commentUpdateForm.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/createComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/createReComment.tsx
  app/(beforeLogin)/search/_components/continentFilter.tsx
  app/(beforeLogin)/search/_components/filterTabs.tsx
  app/(beforeLogin)/search/_components/themeFilter.tsx
  app/(beforeLogin)/search/_components/type.ts
  app/(beforeLogin)/search/page.tsx
  hook/type.ts
  hook/useFloatingBarHandler.ts
  hook/useUpdatePost.ts
  libs/reactQuery/type.ts
  libs/reactQuery/useCommentMutation.ts
  libs/reactQuery/usePostMutation.ts
  styles/color.ts
  styles/common-button.ts
Labels: medium, 🟢 feat

#96 YG-137 [refactor]: search page, modal & filtering
  apis/postApi.ts
  apis/type.ts
  app/(afterLogin)/createPost/_components/form/selectedTheme.tsx
  app/(afterLogin)/createPost/_components/form/type.ts
  app/(afterLogin)/createPost/_components/overlay/type.ts
  app/(afterLogin)/createPost/_components/region/selectContinent.tsx
  app/(afterLogin)/createPost/_components/region/type.ts
  app/(afterLogin)/detailPost/[postId]/_components/postDetail.tsx
  app/(afterLogin)/updatePost/[postId]/page.tsx
  app/(beforeLogin)/search/_components/continentFilter.tsx
  app/(beforeLogin)/search/_components/themeFilter.tsx
  app/(beforeLogin)/search/page.tsx
  app/(beforeLogin)/survey/_components/survey.util.ts
  app/(beforeLogin)/survey/_components/type.ts
  app/_components/mainRecommend.tsx
  app/_components/mainSearch.tsx
  app/_components/recommend.utils.ts
  app/_components/recommendPagination.tsx
  app/_components/type.ts
  app/_components/userRecommendation/PostList.tsx
  app/_components/userRecommendation/hoverMoreButton.tsx
  app/_components/userRecommendation/realTimeRecommendation.tsx
  app/_components/userRecommendation/recommendationHeader.tsx
  app/_components/userRecommendation/userRecommendation.tsx
  app/clientLayout.tsx
  app/page.tsx
  components/commons/postCard.tsx
  components/commons/searchBar.tsx
  components/commons/searchDropdown.tsx
  components/commons/searchDropdownMap.tsx
  components/commons/searchResults.tsx
  components/commons/sortDropdown.tsx
  components/commons/type.ts
  components/layouts/_components/headerSearch.tsx
  components/layouts/header.tsx
  constants/continents.ts
  constants/type.ts
  hook/type.ts
  libs/reactQuery/type.ts
  libs/searchStore.ts
  libs/type.ts
  public/icons/grey_search.svg
  public/icons/x-circle.svg
  types/continent.ts
  types/post.ts
  types/sortCondition.ts
  types/theme.ts
Labels: 💡 refactor

#98 YG-139 [refactor]: memo address refactor
  app/(afterLogin)/post/_components/common/useCommonPost.tsx
  app/(afterLogin)/post/_components/form/addressSelection.tsx
  app/(afterLogin)/post/_components/form/formSelector.tsx
  app/(afterLogin)/post/_components/form/type.ts
  app/(afterLogin)/post/create/_components/commonPost.tsx
  app/(afterLogin)/post/create/memo/page.tsx
  app/(afterLogin)/post/detail/[postId]/_components/floating/floatingBarHandler.ts
  app/(afterLogin)/post/detail/[postId]/_components/section/detailSection.tsx
  app/_components/userRecommendation/recommendationHeader.tsx
Labels: 🐞 fix, 🎁 style, 💡 refactor

#99 YG-141 [refactor]: main style
  app/(beforeLogin)/survey/_components/recommendPostCard.tsx
  app/(beforeLogin)/survey/_components/surveyResult.tsx
  app/(beforeLogin)/survey/page.tsx
  app/_components/mainDesc.tsx
  app/_components/mainImages.tsx
  app/_components/mainIntro.tsx
  app/_components/mainThemeBanner.tsx
  app/_components/polaroid.tsx
  app/_components/recommendText.tsx
  constants/mainImages.ts
  public/images/main-03.svg
  public/images/main-stamp-04.svg
Labels: 🎁 style, 💡 refactor

#101 YG-88 [feat] : api user info
  apis/api.utils.ts
  apis/postApi.ts
  apis/userApi.ts
  app/(afterLogin)/post/_components/common/useCommonPost.tsx
  app/(afterLogin)/post/_components/overlay/previewPostcard.tsx
  app/(afterLogin)/post/edit/[postId]/page.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/type.ts
  app/(afterLogin)/user/[userId]/_components/myMap/worldMap.tsx
  app/(afterLogin)/user/[userId]/_components/myPost.tsx
  app/(afterLogin)/user/[userId]/_components/myPost/myPosts.tsx
  app/(afterLogin)/user/[userId]/_components/myPost/type.ts
  app/(afterLogin)/user/[userId]/_components/profile/_components/banner.tsx
  app/(afterLogin)/user/[userId]/_components/profile/_components/buttons.tsx
  app/(afterLogin)/user/[userId]/_components/profile/_components/profileContext.tsx
  app/(afterLogin)/user/[userId]/_components/profile/_components/profileImage.tsx
  app/(afterLogin)/user/[userId]/_components/profile/_components/type.ts
  app/(afterLogin)/user/[userId]/_components/profile/editField.tsx
  app/(afterLogin)/user/[userId]/_components/profile/editProfile.tsx
  app/(afterLogin)/user/[userId]/_components/profile/profile.tsx
  app/(afterLogin)/user/[userId]/_components/profile/profileDetails.tsx
  app/(afterLogin)/user/[userId]/_components/profile/type.ts
  app/(afterLogin)/user/[userId]/page.tsx
  app/(afterLogin)/user/[userId]/type.ts
  app/_components/userRecommendation/type.ts
  app/_components/userRecommendation/userRecommendation.tsx
  components/commons/overlay.tsx
  components/commons/postCard.tsx
  components/layouts/_components/headerLogin.tsx
  components/layouts/_components/type.ts
  components/layouts/type.ts
  libs/reactQuery/useUserMutation.ts
  libs/zustand/login.ts
  libs/zustand/type.ts
  public/images/p_bg.png
  public/images/profile.jpg
  public/images/sampleCat.jpeg
  public/images/user/defaultBanner.svg
  public/images/user/sampleProfile.svg
  types/user.ts
  utils/form.utils.ts
  utils/setImage.utils.ts
Labels: medium, 🟢 feat

#100 Yg 144 refactor main layout
  app/_components/mainImages.tsx
  app/_components/mainSearch.tsx
  app/layout.tsx
  components/commons/rankCard.tsx
  components/commons/skeleton.tsx
  components/commons/type.ts
  constants/mainImages.ts
  hook/useRecommendPagination.ts
  public/images/main-02.svg
  public/images/main-02.webp
  public/images/main-03.svg
  public/images/main-03.webp
Labels: 🐞 fix, 💡 refactor

#103 YG-146 [refactor]: comment pagination
  apis/commentApi.ts
  apis/type.ts
  app/(afterLogin)/post/detail/[postId]/page.tsx
Labels: 💡 refactor

#104 YG-145 [refactor] : ban my page
  apis/mapApi.ts
  apis/userApi.ts
  app/(afterLogin)/post/_components/form/selectedTheme.tsx
  app/(afterLogin)/post/_components/overlay/thumbnailUploader.tsx
  app/(afterLogin)/post/detail/[postId]/_components/section/detailClientSection.tsx
  app/(afterLogin)/post/detail/[postId]/page.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/worldMap.tsx
  app/(afterLogin)/user/[userId]/_components/profile/_components/banner.tsx
  app/(afterLogin)/user/[userId]/_components/profile/_components/profileImage.tsx
  app/(afterLogin)/user/[userId]/_components/profile/editProfile.tsx
  app/(afterLogin)/user/[userId]/_components/profile/profile.tsx
  app/(afterLogin)/user/[userId]/_components/profile/profileDetails.tsx
  app/(afterLogin)/user/[userId]/_components/profile/type.ts
  components/commons/postCard.tsx
  libs/reactQuery/useUserMutation.ts
  next.config.mjs
  public/images/default/thumbnail01.jpg
  public/images/default/thumbnail02.jpg
  utils/randomThumbnail.ts
Labels: High, 🟢 feat, 🐞 fix

#106 YG-150 [refactor]: recommend refactor
  app/(beforeLogin)/search/_components/filterTabs.tsx
  app/(beforeLogin)/search/_components/themeFilter.tsx
  app/(beforeLogin)/search/page.tsx
  app/_components/mainRecommend.tsx
  app/_components/userRecommendation/PostList.tsx
  app/_components/userRecommendation/realTimeRecommendation.tsx
  app/_components/userRecommendation/recommendationHeader.tsx
  app/_components/userRecommendation/userRecommendation.tsx
  types/theme.ts
Labels: 💡 refactor

#107 YG-153 [refactor]: theme banner refactor
  app/_components/mainThemeBanner.tsx
  constants/themeBannerTexts.ts
  public/images/CULTURE.svg
  public/images/HISTORY.svg
  types/theme.ts
Labels: 🎁 style, 💡 refactor

#109 YG-155 [refactor]: post,comment,postCard,recommendCard user profile refactor
  app/(afterLogin)/post/_components/overlay/previewPostcard.tsx
  app/(afterLogin)/post/detail/[postId]/_components/comment/_components/commentContents.tsx
  app/(afterLogin)/post/detail/[postId]/_components/comment/_components/type.ts
  app/(afterLogin)/post/detail/[postId]/_components/comment/comment.tsx
  app/(afterLogin)/post/detail/[postId]/_components/comment/commentBox.tsx
  app/(afterLogin)/post/detail/[postId]/_components/comment/reComment.tsx
  app/(afterLogin)/post/detail/[postId]/_components/comment/type.ts
  app/(afterLogin)/post/detail/[postId]/_components/section/commentSection.tsx
  app/(afterLogin)/user/[userId]/_components/myPost/myPosts.tsx
  app/(beforeLogin)/survey/_components/recommendPostCard.tsx
  app/_components/userRecommendation/PostList.tsx
  components/commons/postCard.tsx
  components/commons/rankCard.tsx
  components/commons/searchResults.tsx
  components/commons/type.ts
  next.config.mjs
  types/post.ts
Labels: 💡 refactor

#110 YG-156 [refactor]: survey prev button style refactor
  app/(beforeLogin)/survey/_components/surveyForm/surveyPrevButton.tsx
  app/(beforeLogin)/survey/_components/surveyForm/surveyQuestion.tsx
  app/(beforeLogin)/survey/_components/surveyForm/surveyQuestionForm.tsx
  app/(beforeLogin)/survey/_components/surveyForm/surveyResult.tsx
  app/(beforeLogin)/survey/_components/surveyForm/type.ts
  app/(beforeLogin)/survey/_components/surveyQuestionForm.tsx
  hook/useSurvey.ts
Labels: 🎁 style, 💡 refactor

#111 YG-151 [feat] user logout
  apis/api.utils.ts
  apis/auth/oauthApi.ts
  apis/auth/signin.ts
  apis/auth/token/access.utils.ts
  apis/auth/token/refresh.utils.ts
  app/(afterLogin)/post/detail/[postId]/_components/comment/createComment.tsx
  app/_components/userRecommendation/userRecommendation.tsx
  app/auth/_components/signin/signinForm.tsx
  app/auth/_components/signup/addInfoForm.tsx
  app/auth/page.tsx
  components/layouts/_components/headerLogin.tsx
  components/layouts/_components/headerNavigate.tsx
  components/layouts/_components/type.ts
  components/layouts/_components/userDialog.tsx
  components/layouts/header.tsx
  constants/navigateList.ts
  hook/type.ts
  hook/useSignin.ts
  hook/useSocialSignup.ts
  libs/reactQuery/type.ts
  libs/reactQuery/useAuthMutation.ts
Labels: 🟢 feat, 🔖 Rename, 🎁 style

#112 YG-158 [style]:image warning clear
  app/(afterLogin)/post/_components/form/formSelector.tsx
  app/(afterLogin)/post/create/_components/commonPost.tsx
  app/_components/mainImages.tsx
  app/_components/mainThemeBanner.tsx
  app/_components/recommendPagination.tsx
  app/_components/userRecommendation/hoverMoreButton.tsx
  components/commons/postCard.tsx
  components/commons/rankCard.tsx
Labels: 🎁 style, 💡 refactor

#113 YG-152 [refactor] : comment pagination
  apis/auth/signin.ts
  app/(afterLogin)/post/detail/[postId]/_components/comment/commentBox.tsx
  app/(afterLogin)/post/detail/[postId]/_components/section/commentSection.tsx
  app/(afterLogin)/post/detail/[postId]/_components/section/type.ts
  app/(afterLogin)/post/detail/[postId]/page.tsx
  components/commons/pagination.tsx
Labels: Low, 💬 Comment, 💡 refactor

#114 YG-160 [refactor] : create post 2
  app/(afterLogin)/post/_components/calendar/calendar.tsx
  app/(afterLogin)/post/_components/calendar/calendar.utils.tsx
  app/(afterLogin)/post/_components/form/formSelector.tsx
  app/(afterLogin)/post/_components/form/selectedTheme.tsx
  app/(afterLogin)/post/_components/form/themeSelection.tsx
  app/(afterLogin)/post/_components/form/type.ts
  app/(afterLogin)/post/create/_components/commonPost.tsx
  app/(afterLogin)/post/create/_components/templateBox.tsx
  app/(afterLogin)/post/detail/[postId]/_components/floating/floatingBarHandler.ts
  app/(afterLogin)/post/edit/[postId]/_components/freeForm.tsx
  app/(afterLogin)/post/edit/[postId]/_components/memoForm.tsx
  app/(afterLogin)/post/edit/[postId]/_components/postForm.tsx
  app/(afterLogin)/post/edit/[postId]/_components/type.ts
  app/(afterLogin)/post/edit/[postId]/page.tsx
  components/layouts/_components/headerLogin.tsx
  components/layouts/header.tsx
  libs/zustand/type.ts
Labels: 🎁 style, 💡 refactor

#115 YG-162 [refactor] : search re-render
  app/(beforeLogin)/search/_components/filterTabs.tsx
  app/(beforeLogin)/search/_components/postSection.tsx
  app/(beforeLogin)/search/_components/themeFilter.tsx
  app/(beforeLogin)/search/_components/type.ts
  app/(beforeLogin)/search/page.tsx
  app/_components/userRecommendation/realTimeRecommendation.tsx
  components/commons/sortDropdown.tsx
  components/commons/type.ts
  constants/sorts.ts
  types/sortCondition.ts
Labels: 🔖 Rename, 🎁 style, 💡 refactor

#116 YG-164 [refactor] : footer 기능 수정 및 생성
  components/layouts/_components/type.ts
  components/layouts/footer.tsx
  components/layouts/layout.tsx
  package-lock.json
  package.json
Labels: Low, 🎁 style, 💡 refactor

#117 YG-166 [refactor] : search modal
  app/_components/mainSearch.tsx
  app/clientLayout.tsx
  components/layouts/_components/headerSearch.tsx
  components/layouts/_components/headerSearchModal.tsx
  components/layouts/_components/search/modalContent.tsx
  components/layouts/_components/search/modalTitle.tsx
  components/layouts/_components/search/type.ts
Labels: 🟢 feat, 🔖 Rename, 💡 refactor

#118 YG-161 [refactor]: save temp post data
  app/(afterLogin)/post/_components/common/useCommonPost.tsx
  app/(afterLogin)/post/edit/[postId]/_components/postForm.tsx
  app/(afterLogin)/post/edit/[postId]/page.tsx
Labels: 💡 refactor

#119 YG-171 [refactor]: survey scroll, other post button
  app/(beforeLogin)/survey/_components/recommendPostCard.tsx
  app/(beforeLogin)/survey/_components/surveyResult.tsx
  app/(beforeLogin)/survey/page.tsx
Labels: 💡 refactor

#120 YG 173 [refactor]: create comment focus & update, delete button
  app/(afterLogin)/post/detail/[postId]/_components/comment/_components/commentMenu.tsx
  app/(afterLogin)/post/detail/[postId]/_components/comment/_components/commentUpdateForm.tsx
  app/(afterLogin)/post/detail/[postId]/_components/comment/comment.tsx
  app/(afterLogin)/post/detail/[postId]/_components/comment/createComment.tsx
  app/(afterLogin)/post/detail/[postId]/_components/comment/type.ts
Labels: 💡 refactor

#121 YG-174 [refactor]: uesCommonPost code refactor
  app/(afterLogin)/post/_components/common/useCommonPost.tsx
  app/(afterLogin)/post/_components/common/useCommonPost/manageCommonLocalStorage.ts
  app/(afterLogin)/post/_components/common/useCommonPost/manageCommonState.ts
  app/(afterLogin)/post/_components/common/useCommonPost/type.ts
  app/(afterLogin)/post/_components/common/useCommonPost/useCommonFormHandling.ts
  app/(afterLogin)/post/_components/common/useCommonPost/useCommonSubmitHandling.ts
Labels: 💡 refactor

#122 YG-177 [style]: useRecommendation
  app/_components/userRecommendation/userRecommendation.tsx
Labels: 🎁 style

#123 YG-167 refactor data fetch (post)
  apis/api.utils.ts
  apis/auth/oauthApi.ts
  apis/auth/token/access.utils.ts
  apis/postApi.ts
  apis/userApi.ts
  app/(afterLogin)/post/_components/common/useCommonPost.tsx
  app/(afterLogin)/post/_components/common/useCommonPost/manageCommonLocalStorage.ts
  app/(afterLogin)/post/_components/common/useCommonPost/type.ts
  app/(afterLogin)/post/_components/common/useCommonPost/useCommonFormHandling.ts
  app/(afterLogin)/post/_components/common/useCommonPost/useCommonSubmitHandling.ts
  app/(afterLogin)/post/_components/editor/editorQuill.tsx
  app/(afterLogin)/post/_components/overlay/uploadOverlay.tsx
  app/(afterLogin)/post/create/_components/selectTemplate.tsx
  app/(afterLogin)/post/create/page.tsx
  app/(afterLogin)/post/detail/[postId]/_components/floating/floatingBarHandler.ts
  app/(afterLogin)/post/detail/[postId]/_components/postDetailClient.tsx
  app/(afterLogin)/post/detail/[postId]/_components/type.ts
  app/(afterLogin)/post/detail/[postId]/page.tsx
  app/(afterLogin)/user/[userId]/_components/myPost/myPosts.tsx
  app/(afterLogin)/user/[userId]/_components/myPost/type.ts
  app/(afterLogin)/user/[userId]/_components/profile/profileDetails.tsx
  app/(afterLogin)/user/[userId]/_components/type.ts
  app/(afterLogin)/user/[userId]/_components/userClient.tsx
  app/(afterLogin)/user/[userId]/page.tsx
  app/(beforeLogin)/search/_components/searchClient.tsx
  app/(beforeLogin)/search/_components/type.ts
  app/(beforeLogin)/search/page.tsx
  app/(beforeLogin)/survey/_components/recommendPostCard.tsx
  app/(beforeLogin)/survey/_components/surveyClient.tsx
  app/(beforeLogin)/survey/page.tsx
  app/_components/userRecommendation/realTimeRecommendation.tsx
  app/_components/userRecommendation/userRecommendation.tsx
  app/auth/page.tsx
  components/commons/searchResults.tsx
  components/layouts/_components/headerLogin.tsx
  libs/queryClient/postQueryClient.ts
  libs/reactQuery/usePostMutation.ts
  next.config.mjs
Labels: 💡 refactor

#124 YG-175 [refactor] : header반응형 수정
  components/layouts/_components/headerLogin.tsx
  components/layouts/_components/userDialog.tsx
Labels: Low, 🎁 style
