Repository mobi-projects/yeogi-client, pull requests merged in 2024-06, with the labels that each got.

#2 Yg 22 [feat]: folder structure
  apis/.gitkeep
  app/(afterLogin)/[postId]/page.tsx
  app/(afterLogin)/[userId]/_components/.gitkeep
  app/(afterLogin)/[userId]/page.tsx
  app/(afterLogin)/createPost/page.tsx
  app/(beforeLogin)/search/page.tsx
  app/(beforeLogin)/signIn/page.tsx
  app/(beforeLogin)/signUp/page.tsx
  components/.gitkeep
  components/commons/.gitkeep
  components/layouts/.gitkeep
  constants/.gitkeep
  hooks/.gitkeep
  libs/.gitkeep
  styles/.gitkeep
  utils/.gitkeep
Labels: High, 🟢 feat

#3 YG-23 ✨[initial] : clsx 의존성 설치
  package-lock.json
  package.json
Labels: High, ✨ initial

#4 YG-24 [hotfix/rename] : 슬러그 이름 변경
  app/(afterLogin)/[id]/_components/.gitkeep
  app/(afterLogin)/[id]/page.tsx
  app/(afterLogin)/createPost/[id]/page.tsx
Labels: High, 🔥 HOTFIX, 🔖 Rename

#9 YG-16 [feat]: common designtoken
  app/(afterLogin)/[userId]/page.tsx
  app/(afterLogin)/createPost/[postId]/page.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  styles/color.ts
  styles/font.ts
  tailwind.config.ts
  utils/.gitkeep
  utils/tailwindUtils.ts
Labels: High, 🟢 feat

#10 YG-26 [docs]: 사용한 스택 및 일정 체크
  README.md
  app/(afterLogin)/[id]/_components/.gitkeep
  app/(afterLogin)/[id]/page.tsx
  app/(afterLogin)/createPost/[id]/page.tsx
Labels: High, 🔴 Remove, 📂 docs

#12 YG-17 [feat]: layout/header
  app/layout.tsx
  components/.gitkeep
  components/layouts/.gitkeep
  components/layouts/footer.tsx
  components/layouts/header.tsx
  components/layouts/layout.tsx
  public/icons/search.svg
  public/icons/write.svg
Labels: 🟢 feat

#13 Yg-18 [feat]: layout/footer
  components/layouts/footer.tsx
Labels: 🟢 feat

#14 YG-29 [feat] : common-searchBar
  components/commons/searchBar.tsx
Labels: medium, 🟢 feat

#16 YG-21 [feat]: common pagination
  app/page.tsx
  components/commons/.gitkeep
  components/commons/pagination.tsx
  public/icons/chevron.svg
  utils/generatePages.ts
Labels: medium, 🟢 feat

#15 Yg 27 [feat]: common button 생성 완료
  app/page.tsx
  components/commons/button.tsx
  package-lock.json
  package.json
Labels: High, 🟢 feat

#18 YG-13 [feat]: input 공용 컴포넌트 생성
  components/commons/input.tsx
Labels: High, 🟢 feat

#19 YG-32 [feat]: common-overlay 생성
  app/page.tsx
  components/commons/button.tsx
  components/commons/overlay.tsx
Labels: High, 🟢 feat

#21 YG-31 [feat] : common comment and re-comment
  app/page.tsx
  components/commons/comment.tsx
  components/commons/pagination.tsx
  components/commons/reComment.tsx
  components/layouts/header.tsx
  public/icons/comment.svg
  public/icons/like.svg
  public/images/comment-bg.svg
  public/images/comment-tape.svg
  public/images/re-comment-bg.svg
  public/images/re-comment-tape.svg
  tailwind.config.ts
Labels: medium, 🟢 feat

#22 Yg-33 [feat]: selected post template
  app/(afterLogin)/createPost/_components/templateBox.tsx
  app/(afterLogin)/createPost/_components/type.ts
  app/(afterLogin)/createPost/page.tsx
  app/(afterLogin)/freeForm/page.tsx
  app/(afterLogin)/memoForm/page.tsx
  components/layouts/header.tsx
  public/images/post-template1.svg
  public/images/post-template2.svg
  styles/color.ts
Labels: medium, 🟢 feat

#23 YG 15 [feat] : common postcard 생성
  app/(afterLogin)/detailPost/[postId]/page.tsx
  app/page.tsx
  components/commons/postCard.tsx
  components/commons/searchBar.tsx
  components/commons/type.ts
  public/icons/comment.svg
  public/icons/gps.svg
  public/icons/like.svg
Labels: medium, 🟢 feat

#24 YG-15 [fix] : postCard Link수정 및 searchBar 아이콘 수정
  components/commons/postCard.tsx
  components/commons/searchBar.tsx
  public/icons/searchbar.svg
Labels: 🐞 fix

#27 YG-39 [feat]: editor
  README.md
  app/(afterLogin)/createPost/_components/editorQuill.tsx
  app/(afterLogin)/freeForm/page.tsx
  app/globals.css
  package-lock.json
  package.json
Labels: medium, 🟢 feat, 📂 docs

#29 YG-41 [fix]: overlay
  app/_page.tsx
  components/commons/overlay.tsx
  public/icons/black_check.svg
  public/icons/white_arrow-left.svg
  public/icons/white_check.svg
Labels: High, 🐞 fix

#31 YG-43 [feat] : common-form
  app/(afterLogin)/createPost/_components/calendar.tsx
  app/(afterLogin)/createPost/_components/editorQuill.tsx
  app/(afterLogin)/createPost/_components/form/form.tsx
  app/(afterLogin)/createPost/_components/form/formBtn.tsx
  app/(afterLogin)/createPost/_components/form/formOverlay.tsx
  app/(afterLogin)/createPost/_components/form/formSelector.tsx
  app/(afterLogin)/createPost/_components/type.ts
  app/(afterLogin)/freeForm/page.tsx
  app/globals.css
  components/commons/overlay.tsx
  components/commons/type.ts
  components/layouts/header.tsx
  utils/calendarUtils.tsx
Labels: medium, 🟢 feat, 🐞 fix

#30 YG-44 [feat]: fail modal 생성 완료
  app/_page.tsx
  components/commons/failModal.tsx
  components/commons/overlay.tsx
  components/commons/type.ts
  public/icons/unhappy.svg
  styles/color.ts
Labels: medium, 🟢 feat, 💡 refactor

#32 YG-45 [feat]: thumbnail overlay
  README.md
  app/(afterLogin)/createPost/_components/thumbnailUploader.tsx
  app/(afterLogin)/createPost/_components/type.ts
  app/(afterLogin)/memoForm/page.tsx
  app/(afterLogin)/user/[userId]/page.tsx
  app/_page.tsx
  public/icons/image.svg
Labels: medium, 🟢 feat, 📂 docs

#33 YG-42 [feat] : floatingbar
  app/(afterLogin)/detailPost/[postId]/_components/floatingBar.tsx
  app/(afterLogin)/detailPost/[postId]/_components/floatingButton.tsx
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/(afterLogin)/detailPost/[postId]/page.tsx
  components/commons/postCard.tsx
  public/icons/arrow_up.svg
  public/icons/floatinglike.svg
  public/icons/share.svg
Labels: medium, 🟢 feat

#34 YG-49 [refactor]: overlay 3차 수정
  components/commons/overlay.tsx
  components/commons/type.ts
Labels: High, 💡 refactor

#35 YG-46 [feat]: postcard preview overlay
  app/(afterLogin)/createPost/_components/form/calendar.tsx
  app/(afterLogin)/createPost/_components/form/editorQuill.tsx
  app/(afterLogin)/createPost/_components/form/formBtn.tsx
  app/(afterLogin)/createPost/_components/previewPostcard.tsx
  app/(afterLogin)/createPost/_components/templateBox.tsx
  app/(afterLogin)/createPost/_components/thumbnailUploader.tsx
  app/(afterLogin)/createPost/_components/type.ts
  app/(afterLogin)/memoForm/page.tsx
  app/globals.css
  components/commons/overlay.tsx
  components/commons/postCard.tsx
  components/commons/type.ts
  next.config.mjs
  public/images/sampleThumbnail.svg
Labels: medium, 🟢 feat

#36 YG-51 [feat] : common-sortDropDown
  app/_components/mainPosts.tsx
  components/commons/sortButton.tsx
  components/commons/sortDropdown.tsx
  components/commons/type.ts
  constants/sortButton.ts
  public/icons/list.svg
Labels: medium, 🟢 feat

#37 YG-54 [feat] : 마이페이지 지도 생성 완료
  app/(afterLogin)/user/[userId]/_components/pin.tsx
  app/(afterLogin)/user/[userId]/_components/type.ts
  app/(afterLogin)/user/[userId]/_components/worldMap.tsx
  app/(afterLogin)/user/[userId]/_components/worldMapHandlers.ts
  app/(afterLogin)/user/[userId]/page.tsx
  components/commons/button.tsx
  public/images/map.svg
  public/images/pin.svg
Labels: medium, 🟢 feat

#40 YG-56 [feat]: es hangul
  components/commons/searchBar.tsx
  components/commons/type.ts
  hooks/.gitkeep
  hooks/type.ts
  hooks/useSearch.ts
  package-lock.json
  package.json
Labels: High, 🟢 feat, 💡 refactor

#41 YG-59 [feat]: free-form
  app/(afterLogin)/createPost/[postId]/page.tsx
  app/(afterLogin)/createPost/_components/form/editorQuill.tsx
  app/(afterLogin)/createPost/_components/type.ts
  app/(afterLogin)/createPost/_components/uploadOverlay.tsx
  app/(afterLogin)/createPost/freeForm/page.tsx
  app/(afterLogin)/createPost/memoForm/page.tsx
  app/(afterLogin)/createPost/page.tsx
  app/(afterLogin)/freeForm/page.tsx
  app/globals.css
Labels: medium, 🟢 feat

#42 YG-57 [feat]: search page
  apis/mockPosts.ts
  app/(afterLogin)/createPost/_components/form/calendar.tsx
  app/(afterLogin)/createPost/_components/form/calendarUtils.tsx
  app/(beforeLogin)/search/page.tsx
  app/_components/mainPosts.tsx
  app/_page.tsx
  components/commons/pagination.tsx
  components/commons/searchBar.tsx
  components/commons/searchResults.tsx
  components/commons/sortButton.tsx
  components/commons/sortDropdown.tsx
  components/commons/type.ts
  components/layouts/footer.tsx
  components/layouts/header.tsx
  constants/sortButton.ts
  hooks/type.ts
  hooks/useSearch.ts
  public/icons/logo_img.svg
  public/icons/logo_text.svg
  utils/filterPosts.ts
  utils/type.ts
Labels: medium, 🟢 feat, 🐞 fix

#44 YG-63 [hotfix]: build error
  app/(afterLogin)/createPost/_components/form/calendar.tsx
  app/(afterLogin)/createPost/_components/form/calendarUtils.tsx
  app/(afterLogin)/createPost/_components/type.ts
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/(afterLogin)/detailPost/[postId]/page.tsx
  app/(beforeLogin)/search/page.tsx
  app/(beforeLogin)/signIn/page.tsx
  app/(beforeLogin)/signUp/page.tsx
  app/_components/mainPosts.tsx
  app/_page.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: High, 🔥 HOTFIX

#45 Yg 52 [feat] : signin -socialLogin publish
  apis/.gitkeep
  app/(beforeLogin)/_auth/signin/addSigninForm.tsx
  app/(beforeLogin)/_auth/signin/socialLoginButton.tsx
  app/(beforeLogin)/_auth/signin/socialSigninForm.tsx
  app/(beforeLogin)/_auth/signin/type.ts
  constants/socialButton.ts
  public/icons/google.svg
  public/icons/kakao.svg
  public/icons/naver_icon 1.svg
  styles/color.ts
Labels: High, 🟢 feat, 🎁 style

#46 YG-66 [fix]: error fix
  app/(beforeLogin)/_auth/signin/socialSigninForm.tsx
  app/(beforeLogin)/_auth/signin/type.ts
  app/_components/mainPosts.tsx
  components/commons/postCard.tsx
  components/commons/sortDropdown.tsx
Labels: High, 🐞 fix

#39 YG-47 [feat]: my-info
  app/(afterLogin)/createPost/_components/form/formOverlay.tsx
  app/(afterLogin)/user/[userId]/_components/editProfile.tsx
  app/(afterLogin)/user/[userId]/_components/editProfile/editField.tsx
  app/(afterLogin)/user/[userId]/_components/editProfile/profileImage.tsx
  app/(afterLogin)/user/[userId]/_components/profile.tsx
  app/(afterLogin)/user/[userId]/page.tsx
  app/(afterLogin)/user/[userId]/type.ts
  public/icons/edit.svg
  public/icons/photoIcon.svg
  public/images/p_bg.png
  public/images/profile.jpg
  public/images/메롱고.jpeg
  tailwind.config.ts
Labels: 🟢 feat, 🐞 fix, 💡 refactor

#47 YG-68 [feat]: api post detail
  apis/commentApi.ts
  apis/postApi.ts
  apis/type.ts
  apis/userApi.ts
  app/(afterLogin)/detailPost/[postId]/_components/commentBox.tsx
  app/(afterLogin)/detailPost/[postId]/_components/createComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/freeFormDetail.tsx
  app/(afterLogin)/detailPost/[postId]/_components/likeToComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/(afterLogin)/detailPost/[postId]/page.tsx
  app/(afterLogin)/detailPost/[postId]/type.ts
  app/layout.tsx
  components/commons/comment.tsx
  components/commons/type.ts
  components/queryProvider.tsx
  next.config.mjs
  utils/formatDate.ts
  utils/type.ts
Labels: High, 🟢 feat, 💡 refactor

#49 YG-70 [feat]: my page merge
  app/(afterLogin)/createPost/_components/form/formOverlay.tsx
  app/(afterLogin)/user/[userId]/_components/myPost.tsx
  app/(afterLogin)/user/[userId]/_components/wordMap/pin.tsx
  app/(afterLogin)/user/[userId]/_components/wordMap/type.ts
  app/(afterLogin)/user/[userId]/_components/wordMap/userDetails.tsx
  app/(afterLogin)/user/[userId]/_components/wordMap/worldMapHandlers.ts
  app/(afterLogin)/user/[userId]/_components/worldMap.tsx
  app/(afterLogin)/user/[userId]/page.tsx
Labels: medium, 🟢 feat

#51 YG-65 [feat] : common signin / signup (미완성)
  apis/auth/signin.ts
  apis/auth/storageUtils.ts
  app/(beforeLogin)/_auth/signin/signinForm.tsx
  app/(beforeLogin)/_auth/signin/type.ts
  app/(beforeLogin)/_auth/signup/ageButton.tsx
  app/(beforeLogin)/_auth/signup/signupForm.tsx
  app/(beforeLogin)/_auth/signup/type.ts
  app/(beforeLogin)/signIn/page.tsx
  app/(beforeLogin)/signUp/page.tsx
  components/commons/input.tsx
  components/layouts/header.tsx
  constants/ageButton.ts
  constants/signinSchema.ts
  hook/type.ts
  next.config.mjs
Labels: High, 🟢 feat

#50 YG-67 [api]: get & create post
  README.md
  apis/mockPosts.ts
  apis/postApi.ts
  apis/type.ts
  app/(afterLogin)/createPost/_components/form/calendar.tsx
  app/(afterLogin)/createPost/_components/form/calendarUtils.tsx
  app/(afterLogin)/createPost/_components/form/countriesSearch.tsx
  app/(afterLogin)/createPost/_components/form/editorQuill.tsx
  app/(afterLogin)/createPost/_components/form/formBtn.tsx
  app/(afterLogin)/createPost/_components/form/formInputs.tsx
  app/(afterLogin)/createPost/_components/form/formSelector.tsx
  app/(afterLogin)/createPost/_components/form/selectCalendar.tsx
  app/(afterLogin)/createPost/_components/form/selectContinent.tsx
  app/(afterLogin)/createPost/_components/previewPostcard.tsx
  app/(afterLogin)/createPost/_components/thumbnailUploader.tsx
  app/(afterLogin)/createPost/_components/type.ts
  app/(afterLogin)/createPost/_components/uploadOverlay.tsx
  app/(afterLogin)/createPost/freeForm/page.tsx
  app/(afterLogin)/createPost/memoForm/page.tsx
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/(afterLogin)/detailPost/[postId]/page.tsx
  app/_components/mainPosts.tsx
  app/_page.tsx
  app/error.tsx
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  app/yeogi.svg
  components/commons/overlay.tsx
  components/commons/postCard.tsx
  components/commons/searchResults.tsx
  components/commons/sortDropdown.tsx
  components/commons/type.ts
  components/layouts/layout.tsx
  components/queryProvider.tsx
  constants/sorts.ts
  data/countries.ts
  hook/type.ts
  hook/useCountrySearch.ts
  libs/.gitkeep
  libs/store.ts
  package-lock.json
  package.json
  public/images/sampleProfile.svg
  public/next.svg
  public/vercel.svg
  utils/filterPosts.ts
  utils/sessionStorage.ts
  utils/type.ts
Labels: High, 🟢 feat, 📂 docs

#52 YG-71 [hotfix]: build error fixed (01)
  app/(afterLogin)/createPost/freeForm/page.tsx
  app/(afterLogin)/createPost/memoForm/page.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/pin.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/type.ts
  app/(afterLogin)/user/[userId]/_components/myMap/userDetails.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/worldMapHandlers.ts
  app/(afterLogin)/user/[userId]/_components/myPost.tsx
  app/(afterLogin)/user/[userId]/_components/worldMap.tsx
  app/layout.tsx
  app/yeogi.svg
  utils/sessionStorage.ts
Labels: High, 🔥 HOTFIX

#53 YG-73 [refactor]: comment
  apis/commentApi.ts
  apis/type.ts
  app/(afterLogin)/detailPost/[postId]/_components/commentBox.tsx
  app/(afterLogin)/detailPost/[postId]/_components/createComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/(beforeLogin)/search/page.tsx
  components/commons/comment.tsx
  components/commons/failModal.tsx
  components/commons/likeButton.tsx
  components/commons/pagination.tsx
  components/commons/type.ts
Labels: medium, 🟢 feat, 🐞 fix, 💡 refactor

#55 YG-76 [feat] post success, fail overlay
  apis/mapApi.ts
  apis/type.ts
  app/(afterLogin)/createPost/_components/calendar/calendar.tsx
  app/(afterLogin)/createPost/_components/calendar/calendarUtils.tsx
  app/(afterLogin)/createPost/_components/calendar/selectCalendar.tsx
  app/(afterLogin)/createPost/_components/calendar/type.ts
  app/(afterLogin)/createPost/_components/editor/editorQuill.tsx
  app/(afterLogin)/createPost/_components/editor/reactQuill.ts
  app/(afterLogin)/createPost/_components/editor/type.ts
  app/(afterLogin)/createPost/_components/form/formBtn.tsx
  app/(afterLogin)/createPost/_components/form/formInputs.tsx
  app/(afterLogin)/createPost/_components/form/formSelector.tsx
  app/(afterLogin)/createPost/_components/form/type.ts
  app/(afterLogin)/createPost/_components/overlay/previewPostcard.tsx
  app/(afterLogin)/createPost/_components/overlay/routerOverlay.tsx
  app/(afterLogin)/createPost/_components/overlay/thumbnailUploader.tsx
  app/(afterLogin)/createPost/_components/overlay/type.ts
  app/(afterLogin)/createPost/_components/overlay/uploadOverlay.tsx
  app/(afterLogin)/createPost/_components/region/countriesSearch.tsx
  app/(afterLogin)/createPost/_components/region/countrySearchBar.tsx
  app/(afterLogin)/createPost/_components/region/selectContinent.tsx
  app/(afterLogin)/createPost/_components/region/type.ts
  app/(afterLogin)/createPost/_components/type.ts
  app/(afterLogin)/createPost/_components/uploadOverlay.tsx
  app/(afterLogin)/createPost/freeForm/page.tsx
  app/(afterLogin)/createPost/memoForm/page.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/commentBox.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/createComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/likeToComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/type.ts
  app/(afterLogin)/detailPost/[postId]/_components/floating/floatingBar.tsx
  app/(afterLogin)/detailPost/[postId]/_components/floating/floatingButton.tsx
  app/(afterLogin)/detailPost/[postId]/_components/floating/type.ts
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/(afterLogin)/detailPost/[postId]/page.tsx
  app/(afterLogin)/detailPost/[postId]/type.ts
  app/(afterLogin)/user/[userId]/_components/myMap/mapHandlers.ts
  app/(afterLogin)/user/[userId]/_components/myMap/pin.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/type.ts
  app/(afterLogin)/user/[userId]/_components/myMap/worldMap.tsx
  app/(afterLogin)/user/[userId]/_components/profile/editField.tsx
  app/(afterLogin)/user/[userId]/_components/profile/editProfile.tsx
  app/(afterLogin)/user/[userId]/_components/profile/profile.tsx
  app/(afterLogin)/user/[userId]/_components/profile/profileImage.tsx
  app/(afterLogin)/user/[userId]/_components/profile/type.ts
  app/(afterLogin)/user/[userId]/_components/userDetails.tsx
  app/(afterLogin)/user/[userId]/_components/worldMap.tsx
  app/(afterLogin)/user/[userId]/page.tsx
  components/commons/overlay.tsx
  data/countries.ts
  hook/type.ts
  hook/useCountrySearch.ts
  libs/store.ts
  libs/storePin.ts
  libs/type.ts
  next.config.mjs
Labels: High, 🔖 Rename, 🎁 style

#57 YG-77 [feat]: delete comment
  apis/commentApi.ts
  apis/mapApi.ts
  apis/postApi.ts
  apis/type.ts
  apis/userApi.ts
  app/(afterLogin)/createPost/_components/overlay/uploadOverlay.tsx
  app/(afterLogin)/createPost/freeForm/page.tsx
  app/(afterLogin)/createPost/memoForm/page.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/commentDeleteButton.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/createComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/type.ts
  app/(afterLogin)/detailPost/[postId]/page.tsx
  components/commons/comment.tsx
  components/commons/deleteModal.tsx
  components/commons/overlay.tsx
  components/commons/successToFailModal.tsx
  components/commons/type.ts
  libs/commentStore.ts
  libs/modalStore.ts
  libs/pinStore.ts
  libs/type.ts
  public/icons/smile.svg
  public/icons/trash.svg
  utils/fetchFormAPI.ts
Labels: medium, 🟢 feat, 🔖 Rename, 💡 refactor

#58 YG-83 [HOTFIX]: success to fail modal
  app/(afterLogin)/detailPost/[postId]/_components/comment/commentDeleteButton.tsx
  app/(afterLogin)/detailPost/[postId]/page.tsx
  app/(beforeLogin)/_auth/signin/signinForm.tsx
  components/commons/comment.tsx
  components/commons/successToFailModal.tsx
  libs/modalStore.ts
  libs/pinStore.ts
  libs/store.ts
Labels: 🔥 HOTFIX

#61 YG-84 [refactor]: comment (create/update/delete)
  apis/commentApi.ts
  app/(afterLogin)/detailPost/[postId]/_components/comment/commentBox.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/commentMenu.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/commentUpdateForm.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/createComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/type.ts
  app/(afterLogin)/detailPost/[postId]/page.tsx
  components/commons/comment.tsx
  components/commons/type.ts
  hook/type.ts
  hook/useCommentMutation.ts
  libs/commentStore.ts
  libs/type.ts
Labels: medium, 💡 refactor

#60 YG-81 [feat] : post update delete
  apis/mockPosts.ts
  apis/postApi.ts
  apis/type.ts
  app/(afterLogin)/createPost/_components/editor/editorQuill.tsx
  app/(afterLogin)/createPost/_components/editor/reactQuill.ts
  app/(afterLogin)/createPost/_components/editor/type.ts
  app/(afterLogin)/createPost/_components/form/formBtn.tsx
  app/(afterLogin)/createPost/_components/form/formInputs.tsx
  app/(afterLogin)/createPost/_components/form/formSelector.tsx
  app/(afterLogin)/createPost/_components/form/type.ts
  app/(afterLogin)/createPost/freeForm/page.tsx
  app/(afterLogin)/createPost/memoForm/page.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/createComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/comment/likeToComment.tsx
  app/(afterLogin)/detailPost/[postId]/_components/floating/floatingBar.tsx
  app/(afterLogin)/detailPost/[postId]/_components/floating/floatingButton.tsx
  app/(afterLogin)/detailPost/[postId]/_components/floating/type.ts
  app/(afterLogin)/detailPost/[postId]/_components/freeFormDetail.tsx
  app/(afterLogin)/detailPost/[postId]/_components/memoFormDetail.tsx
  app/(afterLogin)/detailPost/[postId]/_components/postDetail.tsx
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/(afterLogin)/detailPost/[postId]/page.tsx
  app/(afterLogin)/updatePost/[postId]/page.tsx
  app/globals.css
  constants/floatingBarIcons.ts
  hook/type.ts
  hook/useFloatingBarHandler.ts
  hook/useHandleScroll.ts
  hook/usePostMutation.ts
  libs/store.ts
  libs/type.ts
  package-lock.json
  package.json
  postcss.config.mjs
  public/build/tailwind.css
  public/icons/trash.svg
  public/images/post-bg.svg
  public/images/tape.svg
  styles/editor-content.css
  tailwind.config.ts
  utils/commonFormUtils.ts
  utils/sessionStorage.ts
  utils/type.ts
  utils/updatePostFunctions.ts
Labels: 🟢 feat, 🐞 fix, 🎁 style, 💡 refactor

#64 YG-82 [feat] : Oauth Signin
  apis/auth/oauthApi.ts
  app/(beforeLogin)/_auth/signin/socialSigninForm.tsx
  app/auth/page.tsx
  app/clientLayout.tsx
  components/layouts/header.tsx
Labels: medium, 🟢 feat

#63 YG-86 [feat]:api worldmap
  apis/mapApi.ts
  app/(afterLogin)/createPost/_components/commonPost.tsx
  app/(afterLogin)/createPost/_components/editor/editorQuill.tsx
  app/(afterLogin)/createPost/freeForm/page.tsx
  app/(afterLogin)/createPost/memoForm/page.tsx
  app/(afterLogin)/detailPost/[postId]/_components/postDetail.tsx
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/(afterLogin)/updatePost/[postId]/page.tsx
  app/(afterLogin)/user/[userId]/_components/myMap/mapHandlers.ts
  app/(afterLogin)/user/[userId]/_components/myMap/type.ts
  app/(afterLogin)/user/[userId]/_components/myMap/worldMap.tsx
  app/(afterLogin)/user/[userId]/page.tsx
  app/(afterLogin)/user/[userId]/type.ts
  hook/useCommonPost.ts
  libs/pinStore.ts
  libs/type.ts
  public/images/pin.svg
  utils/localStorage.ts
  utils/type.ts
  utils/updatePostFunctions.ts
Labels: Low, 🟢 feat, 💡 refactor

#66 YG-95 [feat]: google map api
  app/(afterLogin)/createPost/_components/addressSearch/addressAutoComplete.tsx
  app/(afterLogin)/createPost/_components/addressSearch/type.ts
  app/(afterLogin)/detailPost/[postId]/_components/MapDiv.tsx
  app/(afterLogin)/detailPost/[postId]/_components/type.ts
  app/api/geocode/route.ts
  app/layout.tsx
  global.d.ts
  package-lock.json
  package.json
Labels: 🟢 feat, 📂 docs

#67 YG-97 [feat]: createPost address
  app/(afterLogin)/createPost/_components/address/type.ts
  app/(afterLogin)/createPost/_components/addressSearch/addressAutoComplete.tsx
  app/(afterLogin)/createPost/_components/addressSearch/selectedAddress.tsx
  app/(afterLogin)/createPost/_components/addressSearch/type.ts
  app/(afterLogin)/createPost/_components/form/formInputs.tsx
  styles/google-search.css
Labels: medium, 🟢 feat

#68 YG-98 [refactor]: update post
  apis/postApi.ts
  apis/type.ts
  app/(afterLogin)/createPost/_components/theme/selectedTheme.tsx
  app/(afterLogin)/updatePost/[postId]/page.tsx
  app/_components/mainImages.tsx
  app/_components/mainPosts.tsx
  app/_components/polaroid.tsx
  components/commons/postCard.tsx
  components/commons/searchBar.tsx
  components/commons/sortDropdown.tsx
  components/layouts/footer.tsx
  components/layouts/header.tsx
  constants/theme.ts
  hook/type.ts
  hook/useCommonPost.ts
  hook/usePostMutation.ts
  libs/store.ts
  libs/type.ts
  utils/fetchFormAPI.ts
  utils/type.ts
Labels: medium, 🟢 feat, 🐞 fix

#71 YG-104 [style]: header, footer refactor
  components/layouts/footer.tsx
  components/layouts/header.tsx
Labels: 🎁 style

#72 YG-99 [feat] theme filter
  apis/postApi.ts
  apis/type.ts
  app/(afterLogin)/createPost/_components/overlay/type.ts
  app/(afterLogin)/createPost/_components/region/selectContinent.tsx
  app/(afterLogin)/createPost/_components/theme/selectedTheme.tsx
  app/(afterLogin)/createPost/_components/theme/type.ts
  app/(afterLogin)/detailPost/[postId]/_components/postDetail.tsx
  app/(afterLogin)/updatePost/[postId]/page.tsx
  app/(beforeLogin)/search/page.tsx
  app/_components/mainPosts.tsx
  app/_components/type.ts
  app/globals.css
  components/commons/searchBar.tsx
  components/commons/searchDropdown.tsx
  components/commons/searchDropdownMap.tsx
  components/commons/sortDropdown.tsx
  components/commons/type.ts
  constants/continents.ts
  constants/sorts.ts
  constants/theme.ts
  libs/store.ts
  libs/type.ts
  utils/resetFormData.ts
  utils/type.ts
Labels: medium, 🟢 feat
